import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { Navigation } from '@/components/portfolio/navigation';

export const metadata: Metadata = {
  title: 'Lumino',
  description: 'A human factors design case study exploring a nightlight and companion app for children and caregivers at bedtime.',
};

function Figure({ name, alt, caption, width, height }: { name: string; alt: string; caption: string; width: number; height: number }) {
  return <figure className="case-figure"><div className="case-image"><Image src={`/projects/lumino/${name}.webp`} alt={alt} width={width} height={height} sizes="(max-width: 700px) 84vw, 40vw" /></div><figcaption>{caption}</figcaption></figure>;
}

export default function Lumino() {
  return <div className="homepage-shell" id="top">
    <header className="site-header case-header"><Link href="/" className="case-back">← All projects</Link><Navigation /></header>
    <main className="case-page">
      <section className="case-intro">
        <p className="case-eyebrow">Human factors · Physical product · UX design</p>
        <h1>Lumino</h1>
        <p className="case-deck">A little light. A familiar voice.<br />A gentler transition to independent sleep.</p>
        <p className="case-summary">Lumino is a mushroom-shaped nightlight and companion app concept for children ages 1–5 and their caregivers. It brings a breathing light, bedtime stories, and parent-child communication into one system, designed around the moments when reassurance matters most.</p>
        <dl className="case-facts"><div><dt>Context</dt><dd>ENP 64 · Spring 2026<br />Methods of Human Factors Engineering</dd></div><div><dt>Team</dt><dd>Ginny Dong &amp; Kylinn Ding</dd></div><div><dt>Scope</dt><dd>Research, app design, physical concept, and prototype testing</dd></div></dl>
      </section>
      <div className="case-hero"><Image src="/projects/lumino/render.webp" alt="Lumino concept render with an illuminated mushroom cap and digital clock base" width={1120} height={1360} priority sizes="(max-width: 700px) 84vw, 50vw" /></div>
      <section className="case-section"><p className="case-eyebrow">01 / The challenge</p><h2>Independence should still feel connected.</h2><p>At bedtime, children may need comfort just as parents are trying to step away. Our task analysis mapped both sides of this routine: a child reaching for reassurance, and a caregiver repeatedly deciding whether to return to the room.</p><p>The design question became: how might we give children a simple, tangible source of comfort while helping caregivers stay responsive from another room?</p></section>
      <section className="case-section"><p className="case-eyebrow">02 / Research</p><h2>Designing for two people in the same moment.</h2><p>We combined a CLIMBER analysis of the family’s context, a caregiver questionnaire with nine responses, and a task analysis of bedtime routines. Most children represented in this small sample were ages 3–4.</p><div className="case-insights"><article><h3>Reassurance is part of the routine.</h3><p>Caregivers described storytelling, singing, and talking as ways to help children settle. Most reported returning to the room one or two times during bedtime.</p></article><article><h3>The interaction has to be immediate.</h3><p>A young child in a dark room needs a physical action that does not depend on reading, navigating a screen, or precise finger movements.</p></article><article><h3>Parents need clarity, too.</h3><p>The parent-facing experience needs to make controls and device state easy to understand during an already demanding routine.</p></article></div></section>
      <section className="case-section"><p className="case-eyebrow">03 / The concept</p><h2>Three ways to reach for comfort.</h2><p>A gently pulsing light offers a visual breathing rhythm. A story button plays preloaded or custom audio. An intercom button lets the child reach a caregiver without leaving bed. These are intended benefits of the concept, rather than measured sleep outcomes.</p><div className="case-gallery"><Figure name="sketch" alt="Mushroom-shaped Lumino concept sketch with side buttons and a clock" caption="The second physical concept moved toward a mushroom form." width={946} height={1396} /><Figure name="cad" alt="Angled CAD view of the mushroom lamp, companion figure, and blue base" caption="CAD exploration of the cap, companion figure, and base." width={1292} height={1246} /></div><h3>Designed around small hands.</h3><p>The proposed silicone cap supports an open-palm pat instead of pinching or twisting. Distinct tactile controls, rounded edges, and a stable base informed the physical design. Material suitability, charging safety, and real-world use would still need validation before a manufactured product.</p></section>
      <section className="case-section"><p className="case-eyebrow">04 / The companion app</p><h2>Keep the child’s device simple.<br />Give caregivers control.</h2><p>The app organizes the experience into Home, Story, Intercom, and Profile. Large controls, a warm palette, and consistent navigation support quick adjustments: changing brightness or volume, choosing audio, talking to a child, and reviewing usage history.</p><div className="case-gallery case-phones"><Figure name="home" alt="Lumino Home app screen showing light brightness, volume, and sleep timer" caption="Home: core lamp settings together in one place." width={544} height={1126} /><Figure name="intercom" alt="Intercom screen with device status and a large hold-to-talk button" caption="Intercom: one prominent hold-to-talk control." width={586} height={1188} /><Figure name="profile" alt="Updated Profile screen showing associated device and usage history" caption="Profile: device information alongside activity history." width={626} height={1274} /></div></section>
      <section className="case-section"><p className="case-eyebrow">05 / Testing &amp; iteration</p><h2>Small moments of hesitation pointed to the next changes.</h2><p>We tested the app prototype with one parent of a four-year-old. The participant completed the core tasks, but the session exposed three points of friction. The findings guided a redesign; the report does not document a follow-up test of those changes.</p><ol className="case-findings"><li><h3>Make scrolling discoverable.</h3><p>Content below the visible area was initially missed. The revised Home screen partially reveals additional content to suggest that the page continues.</p></li><li><h3>Bring related actions together.</h3><p>The participant hesitated when finding playback. We moved the preview control beside “Add,” keeping listening and selecting within the same interaction area.</p></li><li><h3>Make the connected device explicit.</h3><p>Uncertainty about the active device reduced confidence. The redesign added associated-device information to the Profile screen.</p></li></ol><div className="case-gallery case-comparison"><Figure name="story-before" alt="Original Story screen with play controls on the left and Add buttons on the right" caption="Before: preview and Add sit on opposite sides of each story." width={508} height={1058} /><Figure name="story-after" alt="Revised Story screen with playback controls immediately beside Add buttons" caption="After: related controls are grouped together." width={594} height={1210} /></div></section>
      <section className="case-section case-reflection"><p className="case-eyebrow">06 / Reflection</p><h2>Design the reassurance, not just the controls.</h2><p>This project connected emotional needs with physical and digital interactions. Task analysis helped us see bedtime as a shared experience; prototype testing showed how visibility and feedback can affect a caregiver’s confidence.</p><p>The outcome is a researched product concept, physical design exploration, and an iterated app prototype. Next steps would include testing with a broader group of families, evaluating the redesigned screens, and validating the integration between the device and app. The nine survey responses and single usability session offer direction, not evidence of general effectiveness.</p></section>
      <footer className="case-footer"><Link href="/" className="case-back">← Back to all projects</Link><a className="case-back" href="#top">Back to top ↑</a></footer>
    </main>
  </div>;
}
